### ISSUE TITLE
css transitions and transformations don't work

### ISSUE THREAD

**Issue by tedbeer** [clientside/amplesdk#163]
Example of non working CSS transformation:

``` CSS
.header {
    display: inline-block;
}
.header-container:hover .header,
.header:hover {
    transform: rotateX(0deg) rotateY(-180deg) rotateZ(0deg);
    transition: transform 3s ease 0s;
}
```

It work in simple html/css but doesn't work in ample driven page.

You can see the test page here - http://tedbeer.net/test/anim.html
You can download the example code here - http://tedbeer.net/test/anim.zip
